version: '3.7'

services:
  db:
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${USER}
      POSTGRES_HOST_AUTH_METHOD: 'trust'
    healthcheck:
      test: ['CMD', 'pg_isready', '-U', '${USER}']
    ports:
      - 5432:5432

  # db:
  #   image: mysql:5.5
  #   restart: unless-stopped
  #   environment:
  #     MYSQL_ROOT_PASSWORD: root
  #     MYSQL_USER: admin
  #     MYSQL_PASSWORD: password
  #     MYSQL_DATABASE: musira
  #   ports:
  #     - 3306:3306