version: '3.1'

services:
  db:
    image: mysql:5.5
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: admin
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: musira
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost']
      timeout: 20s
      retries: 10
      interval: 5s
    ports:
      - 3306:3306

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    ports:
      - 6379:6379
