name: Update Node.js Version

on:
  schedule:
    - cron: '0 0 * * 0' # Run every Sunday at midnight UTC
  workflow_dispatch:

jobs:
  update-node-version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Setup Node.js
        uses: actions/setup-node@v7

      - name: Get the latest Node.js version
        id: latest-node-version
        run: echo "version=$(curl -sL https://nodejs.org/dist/index.tab | awk 'NR>1 {print $1}' | sort -V | tail -n1)" >> $GITHUB_OUTPUT

      - name: Read current version from .nvmrc
        id: current-node-version
        run: echo "version=$(cat .nvmrc)" >> $GITHUB_OUTPUT

      - name: Compare versions
        id: compare-versions
        run: |
          LATEST_VERSION=${{ steps.latest-node-version.outputs.version }}
          CURRENT_VERSION=${{ steps.current-node-version.outputs.version }}

          if [[ "$LATEST_VERSION" != "$CURRENT_VERSION" ]]; then
            echo "update=true" >> $GITHUB_OUTPUT
          else
            echo "update=false" >> $GITHUB_OUTPUT
          fi

      - name: Update package.json
        if: steps.compare-versions.outputs.update == 'true'
        run: |
          LATEST_VERSION=${{ steps.latest-node-version.outputs.version }}

          if grep -q '"engines"' package.json; then
            sed -i "s/\"node\": \".*\"/\"node\": \">=${LATEST_VERSION#v}\"/g" package.json
          else
            sed -i "/\"workspaces\"/i \\  \"engines\": {\n    \"node\": \">=${LATEST_VERSION#v}\"\n  }," package.json
          fi

      - name: Update .nvmrc
        if: steps.compare-versions.outputs.update == 'true'
        run: echo "${{ steps.latest-node-version.outputs.version }}" > .nvmrc

      - name: Open a PR
        if: steps.compare-versions.outputs.update == 'true'
        uses: peter-evans/create-pull-request@v8
        env:
          GITHUB_TOKEN: ${{ secrets.REPO_SCOPED_TOKEN }}
        with:
          token: ${{ secrets.REPO_SCOPED_TOKEN }}
          branch: update-node-version-${{ github.run_number }}
          title: 'Update Node.js version'
          body: |
            This PR updates the .nvmrc file with the latest Node.js version.
            It also updates the package.json file with the Node engine set to the latest version.
          labels: |
            automation
            update
