name: Tests sur PR

on:
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        project: [angular, nestjs]

    steps:
    - uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '19.x'

    - name: Install dependencies
      run: |
        cd ${{ matrix.project }}
        npm install

    - name: Build
      run: |
        cd ${{ matrix.project }}
        npm build

    - name: Test
      run: |
        cd ${{ matrix.project }}
        npm test
