name: Test and build
on:
  workflow_dispatch:
  push:
    branches:
      - main
    tags:
      - 'v*.*.*'
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: nrwl/nx-set-shas@v3
      - uses: actions/setup-node@v3
        with:
          cache: 'npm'
          node-version-file: '.nvmrc'
      - run: npm i
      - run: npx nx format:check
      - run: npx nx affected -t lint --parallel=3
      - run: npx nx affected -t test --parallel=3 --configuration=ci
  build:
    needs: test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        app: [api, musira]
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          cache: 'npm'
          node-version-file: '.nvmrc'
      - run: npm i
      - run: npx nx -t build --parallel=3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        platforms: 'arm,arm64'
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: |
            ${{ matrix.app }}
          tags: |
            type=schedule
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          # context: '{{defaultContext}}:apps/${{ matrix.app }}'
          context: .
          file: ./apps/${{ matrix.app }}/Dockerfile
          push: true
          platforms: linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm/v8,linux/arm64
          tags: ${{ vars.APP_NAME }}-${{ matrix.app }}:latest
          labels: ${{ steps.meta.outputs.labels }}
      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          if-no-files-found: error
          name: prod
          path: |
            dist/
